-- ============================================================
-- Federal Register Sentinel — Keyword Seed Data
-- Run this after schema.sql to populate the keywords table.
-- Safe to re-run: ON CONFLICT DO NOTHING skips existing rows.
-- ============================================================

BEGIN;

-- ── ANCHOR TERMS (substring match) ──────────────────────────────────────────

INSERT INTO keywords (term, list_type) VALUES
  -- Federal Statutes
  ('animal welfare act',                                        'anchor'),
  ('marine mammal protection act',                              'anchor'),
  ('endangered species act',                                    'anchor'),
  ('migratory bird treaty act',                                 'anchor'),
  ('lacey act',                                                 'anchor'),
  ('horse protection act',                                      'anchor'),
  ('humane methods of slaughter act',                           'anchor'),
  ('humane slaughter act',                                      'anchor'),
  ('wild free-roaming horses and burros act',                   'anchor'),
  ('animal enterprise terrorism act',                           'anchor'),
  ('fur seal act',                                              'anchor'),
  ('bald and golden eagle protection act',                      'anchor'),
  ('great ape conservation act',                                'anchor'),
  ('african elephant conservation act',                         'anchor'),
  ('rhinoceros and tiger conservation act',                     'anchor'),
  ('shark finning prohibition act',                             'anchor'),
  ('pets evacuation and transportation standards act',          'anchor'),
  ('federal meat inspection act',                               'anchor'),
  ('poultry products inspection act',                           'anchor'),
  ('egg products inspection act',                               'anchor'),
  ('twenty-eight hour law',                                     'anchor'),
  ('chimpanzee health improvement maintenance and protection act', 'anchor'),
  ('convention on international trade in endangered species',   'anchor'),
  -- Agency Names
  ('animal and plant health inspection service',                'anchor'),
  ('food safety and inspection service',                        'anchor'),
  ('national marine fisheries service',                         'anchor'),
  ('institutional animal care and use committee',               'anchor'),
  ('animal welfare information center',                         'anchor'),
  -- Factory Farming and Intensive Confinement
  ('factory farming',                                           'anchor'),
  ('factory farm',                                              'anchor'),
  ('concentrated animal feeding operation',                     'anchor'),
  ('intensive confinement',                                     'anchor'),
  ('gestation crate',                                           'anchor'),
  ('gestation stall',                                           'anchor'),
  ('farrowing crate',                                           'anchor'),
  ('sow stall',                                                 'anchor'),
  ('veal crate',                                                'anchor'),
  ('battery cage',                                              'anchor'),
  ('enriched colony cage',                                      'anchor'),
  ('cage-free',                                                 'anchor'),
  ('furnished cage',                                            'anchor'),
  ('foie gras',                                                 'anchor'),
  ('force-fed',                                                 'anchor'),
  ('gavage',                                                    'anchor'),
  ('beak trimming',                                             'anchor'),
  ('debeaking',                                                 'anchor'),
  ('tail docking',                                              'anchor'),
  ('gestation housing',                                         'anchor'),
  -- Animal Research and Experimentation
  ('animal testing',                                            'anchor'),
  ('animal experimentation',                                    'anchor'),
  ('vivisection',                                               'anchor'),
  ('laboratory animal welfare',                                 'anchor'),
  ('research animal welfare',                                   'anchor'),
  ('guide for the care and use of laboratory animals',          'anchor'),
  ('animal care and use committee',                             'anchor'),
  ('pain and distress',                                         'anchor'),
  ('alternatives to animal testing',                            'anchor'),
  ('animal research facility',                                  'anchor'),
  ('registered research facility',                              'anchor'),
  -- Animal Fighting
  ('animal fighting',                                           'anchor'),
  ('cockfighting',                                              'anchor'),
  ('dogfighting',                                               'anchor'),
  ('animal fighting venture',                                   'anchor'),
  ('fighting bird',                                             'anchor'),
  ('fighting dog',                                              'anchor'),
  ('slashers',                                                  'anchor'),
  -- Companion Animal Welfare
  ('puppy mill',                                                'anchor'),
  ('kitten mill',                                               'anchor'),
  ('high-volume breeder',                                       'anchor'),
  ('commercial breeder',                                        'anchor'),
  ('commercial dog breeder',                                    'anchor'),
  ('random source',                                             'anchor'),
  ('class b dealer',                                            'anchor'),
  ('class b license',                                           'anchor'),
  -- Wildlife Trade and Trafficking
  ('wildlife trafficking',                                      'anchor'),
  ('illegal wildlife trade',                                    'anchor'),
  ('wildlife smuggling',                                        'anchor'),
  ('live animal import',                                        'anchor'),
  ('live animal export',                                        'anchor'),
  ('import of wildlife',                                        'anchor'),
  ('export of wildlife',                                        'anchor'),
  ('ivory trade',                                               'anchor'),
  ('ivory ban',                                                 'anchor'),
  ('trophy import',                                             'anchor'),
  ('trophy export',                                             'anchor'),
  ('safari trophy',                                             'anchor'),
  -- ESA Legal Concepts
  ('critical habitat',                                          'anchor'),
  ('incidental take',                                           'anchor'),
  ('incidental take permit',                                    'anchor'),
  ('incidental take statement',                                 'anchor'),
  ('biological opinion',                                        'anchor'),
  ('jeopardy determination',                                    'anchor'),
  ('no jeopardy',                                               'anchor'),
  ('not jeopardize',                                            'anchor'),
  ('species listing',                                           'anchor'),
  ('proposed listing',                                          'anchor'),
  ('final listing',                                             'anchor'),
  ('proposed delisting',                                        'anchor'),
  ('final delisting',                                           'anchor'),
  ('candidate species',                                         'anchor'),
  ('petition to list',                                          'anchor'),
  ('petition to delist',                                        'anchor'),
  ('recovery plan',                                             'anchor'),
  ('recovery program',                                          'anchor'),
  ('recovery strategy',                                         'anchor'),
  ('conservation agreement',                                    'anchor'),
  ('safe harbor agreement',                                     'anchor'),
  ('candidate conservation agreement',                          'anchor'),
  ('no surprises rule',                                         'anchor'),
  ('section 7 consultation',                                    'anchor'),
  ('section 4 listing',                                         'anchor'),
  ('section 10 permit',                                         'anchor'),
  ('4(d) rule',                                                 'anchor'),
  ('distinct population segment',                               'anchor'),
  ('evolutionarily significant unit',                           'anchor'),
  ('range-wide status review',                                  'anchor'),
  -- Humane Slaughter
  ('humane slaughter',                                          'anchor'),
  ('humane methods of slaughter',                               'anchor'),
  ('humane handling',                                           'anchor'),
  ('ante-mortem inspection',                                    'anchor'),
  ('post-mortem inspection',                                    'anchor'),
  ('stunning requirement',                                      'anchor'),
  ('ritual slaughter',                                          'anchor'),
  ('downer animal',                                             'anchor'),
  ('non-ambulatory animal',                                     'anchor'),
  -- AWA-Regulated Activities
  ('animal dealer',                                             'anchor'),
  ('animal exhibitor',                                          'anchor'),
  ('animal transporter',                                        'anchor'),
  ('animal carrier',                                            'anchor'),
  ('regulated activity',                                        'anchor'),
  ('dealer license',                                            'anchor'),
  ('exhibitor license',                                         'anchor'),
  ('annual report of animals',                                  'anchor'),
  -- Marine Animal Protection
  ('shark finning',                                             'anchor'),
  ('shark fin',                                                 'anchor'),
  ('shark fin ban',                                             'anchor'),
  ('finning prohibition',                                       'anchor'),
  ('whaling',                                                   'anchor'),
  ('commercial whaling',                                        'anchor'),
  ('aboriginal subsistence whaling',                            'anchor'),
  ('sealskin import',                                           'anchor'),
  ('seal hunt',                                                 'anchor'),
  ('sea turtle take',                                           'anchor'),
  ('dolphin-safe',                                              'anchor'),
  -- Fur Industry
  ('fur farm',                                                  'anchor'),
  ('fur farming',                                               'anchor'),
  ('mink farm',                                                 'anchor'),
  ('fox farm',                                                  'anchor'),
  ('fur trapping regulation',                                   'anchor'),
  ('trapping standard',                                         'anchor'),
  -- Predator and Wildlife Management
  ('depredation order',                                         'anchor'),
  ('depredation permit',                                        'anchor'),
  ('lethal removal order',                                      'anchor'),
  ('aerial gunning',                                            'anchor'),
  ('aerial killing',                                            'anchor'),
  ('poison collar',                                             'anchor'),
  ('m-44 device',                                               'anchor'),
  ('leg hold trap',                                             'anchor'),
  ('body-gripping trap',                                        'anchor'),
  ('snare regulation',                                          'anchor'),
  ('wildlife services killing',                                 'anchor'),
  -- Animal Disease Eradication Programs
  ('brucellosis eradication',                                   'anchor'),
  ('brucellosis program',                                       'anchor'),
  ('scrapie eradication',                                       'anchor'),
  ('scrapie program',                                           'anchor'),
  ('scrapie elimination program',                               'anchor'),
  ('chronic wasting disease',                                   'anchor'),
  ('bovine spongiform encephalopathy',                          'anchor'),
  ('mad cow disease',                                           'anchor'),
  ('foot-and-mouth disease',                                    'anchor'),
  ('foot and mouth disease',                                    'anchor'),
  ('classical swine fever',                                     'anchor'),
  ('african swine fever',                                       'anchor'),
  ('newcastle disease',                                         'anchor'),
  ('highly pathogenic avian influenza',                         'anchor'),
  ('low pathogenic avian influenza',                            'anchor'),
  ('equine infectious anemia',                                  'anchor'),
  ('pseudorabies eradication',                                  'anchor'),
  ('johne''s disease program',                                  'anchor'),
  -- Horse and Equine Welfare
  ('horse slaughter',                                           'anchor'),
  ('equine slaughter',                                          'anchor'),
  ('horse soring',                                              'anchor'),
  ('soring',                                                    'anchor'),
  ('action device',                                             'anchor'),
  ('padded horse',                                              'anchor'),
  ('horse tripping',                                            'anchor'),
  ('wild horse management',                                     'anchor'),
  ('wild horse roundup',                                        'anchor'),
  ('horse gather',                                              'anchor'),
  ('burro management',                                          'anchor'),
  ('herd management area',                                      'anchor'),
  -- Miscellaneous
  ('animal welfare',                                            'anchor'),
  ('animal rights',                                             'anchor'),
  ('animal cruelty',                                            'anchor'),
  ('cruelty to animals',                                        'anchor'),
  ('animal abuse',                                              'anchor'),
  ('animal neglect',                                            'anchor')
ON CONFLICT (term, list_type) DO NOTHING;


-- ── ANCHOR TERMS — WORD BOUNDARY (abbreviations, matched with \b...\b) ───────

INSERT INTO keywords (term, list_type) VALUES
  ('AWA',   'anchor_wb'),
  ('MMPA',  'anchor_wb'),
  ('APHIS', 'anchor_wb'),
  ('IACUC', 'anchor_wb'),
  ('CAFO',  'anchor_wb'),
  ('FSIS',  'anchor_wb'),
  ('NMFS',  'anchor_wb'),
  ('USFWS', 'anchor_wb')
ON CONFLICT (term, list_type) DO NOTHING;


-- ── CONTEXT TERMS (+1 point each, threshold = 2) ─────────────────────────────

INSERT INTO keywords (term, list_type) VALUES
  -- Livestock and Farm Animals
  ('livestock',          'context'),
  ('cattle',             'context'),
  ('bovine',             'context'),
  ('swine',              'context'),
  ('hog',                'context'),
  ('pig',                'context'),
  ('poultry',            'context'),
  ('chicken',            'context'),
  ('broiler',            'context'),
  ('layer hen',          'context'),
  ('turkey',             'context'),
  ('duck',               'context'),
  ('goose',              'context'),
  ('equine',             'context'),
  ('horse',              'context'),
  ('mule',               'context'),
  ('donkey',             'context'),
  ('burro',              'context'),
  ('sheep',              'context'),
  ('lamb',               'context'),
  ('goat',               'context'),
  ('bison',              'context'),
  ('feedlot',            'context'),
  ('feed yard',          'context'),
  ('pasture',            'context'),
  ('grazing',            'context'),
  ('rangeland',          'context'),
  ('range management',   'context'),
  ('herd',               'context'),
  ('flock',              'context'),
  ('animal husbandry',   'context'),
  ('animal production',  'context'),
  ('animal agriculture', 'context'),
  ('livestock producer', 'context'),
  ('livestock market',   'context'),
  ('livestock auction',  'context'),
  ('stockyard',          'context'),
  ('packing plant',      'context'),
  ('meatpacking',        'context'),
  ('rendering',          'context'),
  ('rendering plant',    'context'),
  -- Wild Animals and Species
  ('wildlife',           'context'),
  ('wild animal',        'context'),
  ('migratory',          'context'),
  ('migratory bird',     'context'),
  ('game species',       'context'),
  ('nongame species',    'context'),
  ('predator',           'context'),
  ('raptor',             'context'),
  ('waterfowl',          'context'),
  ('songbird',           'context'),
  ('shorebird',          'context'),
  ('neotropical',        'context'),
  ('wild horse',         'context'),
  ('feral horse',        'context'),
  ('feral cat',          'context'),
  ('feral animal',       'context'),
  ('feral population',   'context'),
  ('wolf',               'context'),
  ('gray wolf',          'context'),
  ('grizzly bear',       'context'),
  ('black bear',         'context'),
  ('mountain lion',      'context'),
  ('cougar',             'context'),
  ('puma',               'context'),
  ('jaguar',             'context'),
  ('ocelot',             'context'),
  ('lynx',               'context'),
  ('bobcat',             'context'),
  ('coyote',             'context'),
  ('deer',               'context'),
  ('elk',                'context'),
  ('moose',              'context'),
  ('caribou',            'context'),
  ('bighorn sheep',      'context'),
  ('pronghorn',          'context'),
  ('bald eagle',         'context'),
  ('golden eagle',       'context'),
  ('whooping crane',     'context'),
  ('sandhill crane',     'context'),
  ('sage grouse',        'context'),
  ('greater sage-grouse','context'),
  ('spotted owl',        'context'),
  ('sea turtle',         'context'),
  ('loggerhead turtle',  'context'),
  ('leatherback turtle', 'context'),
  ('hawksbill turtle',   'context'),
  ('sturgeon',           'context'),
  ('salmon',             'context'),
  ('trout',              'context'),
  ('steelhead',          'context'),
  ('paddlefish',         'context'),
  ('amphibian',          'context'),
  ('reptile',            'context'),
  ('tortoise',           'context'),
  ('desert tortoise',    'context'),
  ('gopher tortoise',    'context'),
  ('bat',                'context'),
  ('primate',            'context'),
  ('nonhuman primate',   'context'),
  ('great ape',          'context'),
  ('chimpanzee',         'context'),
  ('gorilla',            'context'),
  ('orangutan',          'context'),
  ('gibbon',             'context'),
  ('macaque',            'context'),
  ('rodent',             'context'),
  ('rabbit',             'context'),
  ('guinea pig',         'context'),
  -- Marine and Aquatic Species
  ('marine mammal',      'context'),
  ('cetacean',           'context'),
  ('whale',              'context'),
  ('dolphin',            'context'),
  ('porpoise',           'context'),
  ('seal',               'context'),
  ('sea lion',           'context'),
  ('walrus',             'context'),
  ('manatee',            'context'),
  ('dugong',             'context'),
  ('polar bear',         'context'),
  ('sea otter',          'context'),
  ('bycatch',            'context'),
  ('incidental catch',   'context'),
  ('incidental bycatch', 'context'),
  ('fishery',            'context'),
  ('commercial fishery', 'context'),
  ('aquaculture',        'context'),
  ('fish farm',          'context'),
  ('mariculture',        'context'),
  ('trawling',           'context'),
  ('bottom trawl',       'context'),
  ('longline',           'context'),
  ('drift net',          'context'),
  ('gillnet',            'context'),
  ('observer program',   'context'),
  -- Habitat and Ecological Terms
  ('habitat',                'context'),
  ('habitat loss',           'context'),
  ('habitat destruction',    'context'),
  ('habitat fragmentation',  'context'),
  ('wildlife corridor',      'context'),
  ('migration corridor',     'context'),
  ('riparian',               'context'),
  ('riparian habitat',       'context'),
  ('wetland',                'context'),
  ('estuary',                'context'),
  ('old growth',             'context'),
  ('old-growth forest',      'context'),
  ('temperate rainforest',   'context'),
  ('native species',         'context'),
  ('invasive species',       'context'),
  ('non-native species',     'context'),
  ('species of concern',     'context'),
  ('protected species',      'context'),
  ('population viability',   'context'),
  -- Captive and Exotic Animals
  ('captive animal',         'context'),
  ('captive wildlife',       'context'),
  ('captive bred',           'context'),
  ('captive breeding',       'context'),
  ('captive propagation',    'context'),
  ('companion animal',       'context'),
  ('shelter animal',         'context'),
  ('stray animal',           'context'),
  ('exotic animal',          'context'),
  ('exotic species',         'context'),
  ('exotic pet',             'context'),
  ('zoological',             'context'),
  ('zoological park',        'context'),
  ('zoo',                    'context'),
  ('aquarium',               'context'),
  ('circus animal',          'context'),
  ('animal sanctuary',       'context'),
  ('wildlife sanctuary',     'context'),
  ('wildlife rehabilitation', 'context'),
  ('sanctuary',              'context'),
  -- Veterinary and Animal Health
  ('veterinary',                   'context'),
  ('veterinarian',                 'context'),
  ('animal health',                'context'),
  ('animal disease',               'context'),
  ('zoonotic',                     'context'),
  ('zoonosis',                     'context'),
  ('animal vaccination',           'context'),
  ('veterinary biologics',         'context'),
  ('feed additive',                'context'),
  ('animal feed',                  'context'),
  ('growth hormone',               'context'),
  ('hormone implant',              'context'),
  ('ractopamine',                  'context'),
  ('antimicrobial resistance',     'context'),
  ('antibiotic use in animals',    'context'),
  ('animal nutrition',             'context'),
  ('herd health',                  'context'),
  ('flock health',                 'context'),
  ('disease surveillance',         'context'),
  ('animal movement',              'context'),
  -- Hunting, Trapping, and Killing
  ('hunting',           'context'),
  ('trapping',          'context'),
  ('snare',             'context'),
  ('trophy hunting',    'context'),
  ('sport hunting',     'context'),
  ('subsistence hunting','context'),
  ('commercial hunting','context'),
  ('poaching',          'context'),
  ('depredation',       'context'),
  ('lethal control',    'context'),
  ('lethal management', 'context'),
  ('predator control',  'context'),
  ('culling',           'context'),
  ('kill permit',       'context'),
  ('take permit',       'context'),
  ('harvest',           'context'),
  -- Trade and Permits
  ('import permit',     'context'),
  ('export permit',     'context'),
  ('wildlife permit',   'context'),
  ('fur',               'context'),
  ('pelt',              'context'),
  ('hide',              'context'),
  ('ivory',             'context'),
  ('bone meal',         'context'),
  ('animal by-product', 'context'),
  ('animal byproduct',  'context'),
  ('rendering',         'context'),
  -- Research and Laboratory Animals
  ('laboratory animal',             'context'),
  ('research animal',               'context'),
  ('animal model',                  'context'),
  ('in vivo',                       'context'),
  ('toxicity testing',              'context'),
  ('bioassay',                      'context'),
  ('animal study',                  'context'),
  ('rodent study',                  'context'),
  ('primate study',                 'context'),
  ('three rs',                      'context'),
  ('replacement reduction refinement', 'context'),
  ('pain and distress',             'context'),
  ('humane endpoint',               'context'),
  -- Slaughter and Processing
  ('slaughter',           'context'),
  ('slaughterhouse',      'context'),
  ('processing facility', 'context'),
  ('processing plant',    'context'),
  ('packing plant',       'context'),
  ('kill floor',          'context'),
  ('ante-mortem',         'context'),
  ('post-mortem',         'context'),
  ('dressing percentage', 'context')
ON CONFLICT (term, list_type) DO NOTHING;


-- ── NOISE TITLE KEYWORDS (NOTICE documents only) ─────────────────────────────

INSERT INTO keywords (term, list_type) VALUES
  -- Aviation and Airspace
  ('airspace',                      'noise_title'),
  ('air traffic control',           'noise_title'),
  ('air route',                     'noise_title'),
  ('instrument approach procedure', 'noise_title'),
  ('instrument flight rule',        'noise_title'),
  ('instrument landing system',     'noise_title'),
  ('airport improvement',           'noise_title'),
  ('runway safety',                 'noise_title'),
  ('runway protection',             'noise_title'),
  ('flight path',                   'noise_title'),
  ('obstacle clearance',            'noise_title'),
  -- Maritime Navigation (non-animal)
  ('drawbridge operation',          'noise_title'),
  ('drawbridge regulation',         'noise_title'),
  ('swing bridge',                  'noise_title'),
  ('bascule bridge',                'noise_title'),
  ('anchorage regulation',          'noise_title'),
  ('traffic separation scheme',     'noise_title'),
  ('aids to navigation',            'noise_title'),
  ('lighthouse',                    'noise_title'),
  ('buoy placement',                'noise_title'),
  ('inland waterway rule',          'noise_title'),
  -- Financial and Securities
  ('securities offering',           'noise_title'),
  ('securities registration',       'noise_title'),
  ('bond issuance',                 'noise_title'),
  ('mortgage-backed security',      'noise_title'),
  ('interest rate determination',   'noise_title'),
  ('bank examination',              'noise_title'),
  ('savings institution',           'noise_title'),
  ('credit union charter',          'noise_title'),
  ('thrift charter',                'noise_title'),
  ('capital adequacy',              'noise_title'),
  -- Telecommunications and Spectrum
  ('spectrum allocation',           'noise_title'),
  ('frequency assignment',          'noise_title'),
  ('broadcast license',             'noise_title'),
  ('radio station license',         'noise_title'),
  ('television broadcast',          'noise_title'),
  ('broadband spectrum',            'noise_title'),
  ('satellite orbit',               'noise_title'),
  -- Nuclear and Radiation
  ('nuclear reactor',               'noise_title'),
  ('nuclear facility license',      'noise_title'),
  ('nuclear power plant',           'noise_title'),
  ('radioactive material license',  'noise_title'),
  ('radiation protection standard', 'noise_title'),
  ('spent nuclear fuel',            'noise_title'),
  -- Transportation Infrastructure
  ('highway construction permit',   'noise_title'),
  ('bridge construction project',   'noise_title'),
  ('tunnel construction',           'noise_title'),
  ('grade crossing',                'noise_title'),
  -- Intellectual Property
  ('patent issuance',               'noise_title'),
  ('patent grant notice',           'noise_title'),
  ('trademark registration notice', 'noise_title'),
  ('copyright registration',        'noise_title'),
  -- Electoral and Federal Pay
  ('federal pay schedule',          'noise_title'),
  ('locality pay adjustment',       'noise_title'),
  ('senior executive service pay',  'noise_title'),
  ('election results certification','noise_title'),
  ('ballot certification',          'noise_title'),
  ('campaign finance reporting',    'noise_title'),
  -- Immigration
  ('visa bulletin',                 'noise_title'),
  ('visa availability',             'noise_title'),
  ('alien registration',            'noise_title'),
  ('immigration fee schedule',      'noise_title')
ON CONFLICT (term, list_type) DO NOTHING;

COMMIT;
